version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/types'
    schedule:
      interval: 'monthly'
    groups:
      npm-dependencies:
        patterns:
          - '*'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      github-actions:
        patterns:
          - '*'
  - package-ecosystem: 'pip'
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      pip-dependencies:
        patterns:
          - '*'
